### ISSUE TITLE
16bit pixels don't encode properly

### ISSUE THREAD

**Issue by nznobody** [animetosho/python-fpnge#1]
*WIP*: I am progressing this issue

However, basically the following code should work, but does not:
```python
import cv2
import numpy as np
import fpnge
import os
print(f"PID: {os.getpid()} {os.getppid()}")


blank_image = np.random.randint(0, high=np.iinfo(np.uint16).max, size=(1,2,3), dtype=np.uint16)
image_bytes = fpnge.fromNP(blank_image)
image_check: cv2.Mat = cv2.imdecode(np.frombuffer(image_bytes, np.uint8), cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
assert image_check.dtype == blank_image.dtype
assert image_check.shape == blank_image.shape
assert (image_check == blank_image).all()  # this line fails, the data is different
```

**Comment by nznobody** [comment]
I have decided this may be in the fpnge library: https://github.com/veluca93/fpnge/issues/14

**Comment by animetosho** [comment]
Forgot to update this to the latest fpnge with various fixes. :|  
Could you try the current version and see if it fixes your issue?

Thanks for reporting by the way!

**Comment by nznobody** [comment]
This appears to not be resolved. I have added some CI testing on my fork and _fixed_ some things I intend to merge back. For now still an issue: https://github.com/nznobody/python-fpnge/runs/7418849286?check_suite_focus=true

Also: https://github.com/veluca93/fpnge/issues/14#issuecomment-1189617286

**Comment by animetosho** [comment]
In addition to [the comment](https://github.com/veluca93/fpnge/issues/14#issuecomment-1190141986) in the other thread, I just realised that the color channel ordering isn't spec'd properly here.  
(NumPy was an afterthought as I was targeting PIL foremost)

I'm currently aiming to not do any channel/endianess conversions to keep this module simple (though if you wish to add them, feel free to do so!), so I'll look at fixing the README (which would mean you'd have to change your code to conform unfortunately).

**Comment by animetosho** [comment]
Updated README. In summary, you'll need to change the type from `np.uint16` to `'>u2'`. Color needs to be ordered with red first, then green, blue, alpha.

Other than my messing up the width/height dimensions (which I think you've fixed), the test seems to pass with the data type change.

Thanks again helping with this horribly written code of mine >_>

**Comment by nznobody** [comment]
Thanks for taking the time to look into this. I'll update my tests and see how they go later today. Would you accept a PR that added a `fromMAT` helper that worked for this?


I am very grateful for you and @veluca93! We are working with large mosaic PNGs that are sometimes 15GB (and sometimes 16bit/px) and it was taking 10-15minutes to save these with PIL/cv2. This appears between 2x-10x faster (if I can get the encoding right)

**Comment by animetosho** [comment]
No issues with more functions - this is just conversion library after all, so the more sources, the easier it is to use :)  
Honestly, it looks like you've done a much better job at this, with those changes, than I have.  
I've added you as a collaborator (I'm hoping it gives you commit rights) as I'm not much of a Python developer myself. So feel free to make changes you think are appropriate (or direct people to your own fork, if you prefer).

Wow, 15GB images! I don't think fpnge is really tuned for images of that size, so will be interesting to how well it works with that.  
From an ideal standpoint, a streaming interface is probably better than requiring the whole image be stored in RAM (and fpnge even over-allocates in a few places). Could be something to investigate in the future.
