### ISSUE TITLE
Remove large test image from git history to reduce download size

### ISSUE THREAD

**Issue by nznobody** [animetosho/python-fpnge#3]
Hello,

I'd like to fix an issue I created in my previous MR. I didn't check the size of the test images I used and now they are checked in adding a lot of download size to this repo. I often install this package via `pip install https://github.com/animetosho/python-fpnge/tarball/master`.

I would recommend replacing the files with a smaller sample or downloading them for tests **and rewriting** master branch history to remove these from the git tree.

I won't have permissions to do this so will let you do it if you like.

Sorry!

**Comment by animetosho** [comment]
No worries - I just replaced them with downscaled versions, which should be sufficient for testing purposes.

Hopefully that solves the issue :)

**Comment by nznobody** [comment]
Looks great, thanks!
